# Generated by Django 5.1.3 on 2024-11-16 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geraGames', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='juegosdatos',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='juegosdatos',
            name='plataforma',
        ),
        migrations.AlterField(
            model_name='review',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geraGames.usuario'),
        ),
        migrations.AddField(
            model_name='juegosdatos',
            name='categoria',
            field=models.ManyToManyField(to='geraGames.categoria'),
        ),
        migrations.AddField(
            model_name='juegosdatos',
            name='plataforma',
            field=models.ManyToManyField(to='geraGames.plataforma'),
        ),
    ]
