# Generated by Django 5.1.3 on 2024-12-09 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geraGames', '0002_remove_juegosdatos_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='juegos/'),
        ),
    ]
