# Generated by Django 5.1.4 on 2024-12-10 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geraGames', '0003_juego_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='visitas',
            field=models.IntegerField(default=0),
        ),
    ]
