# Generated by Django 5.1.4 on 2024-12-10 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geraGames', '0004_juego_visitas'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
