# Generated by Django 5.1.4 on 2024-12-11 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geraGames', '0005_juego_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='usr/'),
        ),
    ]
